/**
 * Bundle assets/js/src/*.js into the single assets/js/main.js the page loads.
 *
 * The source is ES modules so each piece can be read, linted and reasoned about
 * on its own. The output is one classic script for the same reason the CSS is
 * one file: the page is served over one connection, mobile already loses around
 * 700ms to render-blocking resources, and native modules would add a request
 * per file plus a resolution round trip. Loading it as type="module" would also
 * change execution timing, which is not a change worth making by accident.
 *
 * The bundling is deliberately the dumbest thing that works: strip the import
 * and export keywords, concatenate in dependency order. That is sound here only
 * because the modules share one flat namespace with no name collisions and no
 * circular imports, both of which are asserted below rather than assumed. If
 * this ever needs more than that, it needs a real bundler, not a cleverer
 * version of this.
 *
 *   node scripts/build-js.js           write main.js
 *   node scripts/build-js.js --check   verify main.js matches the source
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SRC = path.join(ROOT, "assets", "js", "src");
const OUT = path.join(ROOT, "assets", "js", "main.js");

// Dependency order: each file may only use what is above it.
const ORDER = ["motion.js", "carousel.js", "portfolio.js", "main.js"];

const BANNER = `/* Generated by scripts/build-js.js from assets/js/src/. Do not edit:
   the next build overwrites it. Edit the source module instead. */\n\n`;

const IMPORT = /^\s*import\s+[^;]+?from\s+["'][^"']+["'];?\s*$/gm;
const EXPORT = /^export\s+/gm;

function build() {
  const missing = ORDER.filter((f) => !fs.existsSync(path.join(SRC, f)));
  if (missing.length) throw new Error(`missing source module(s): ${missing.join(", ")}`);

  const present = fs.readdirSync(SRC).filter((f) => f.endsWith(".js"));
  const unlisted = present.filter((f) => !ORDER.includes(f));
  if (unlisted.length) {
    throw new Error(
      `assets/js/src/${unlisted.join(", ")} is not in ORDER in scripts/build-js.js. ` +
        `Add it in dependency order — the bundle is a concatenation, so position is meaning.`,
    );
  }

  const chunks = ORDER.map((file) => {
    const source = fs.readFileSync(path.join(SRC, file), "utf8");
    return source.replace(IMPORT, "").replace(EXPORT, "").replace(/\n{3,}/g, "\n\n").trim();
  });

  const bundle = BANNER + chunks.join("\n\n") + "\n";

  // Nothing may survive that only a module loader would understand.
  const leftover = bundle.match(/^\s*(import|export)\s/m);
  if (leftover) throw new Error(`module syntax survived bundling: ${leftover[0].trim()}`);

  // Two modules declaring the same top-level name would silently collide once
  // the module scopes are gone.
  const names = [...bundle.matchAll(/^(?:const|let|var|class|function)\s+([A-Za-z_$][\w$]*)/gm)]
    .map((m) => m[1]);
  const dupes = names.filter((n, i) => names.indexOf(n) !== i);
  if (dupes.length) throw new Error(`name collision across modules: ${[...new Set(dupes)].join(", ")}`);

  return { bundle, files: ORDER.length };
}

const { bundle, files } = build();
const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";

if (process.argv.includes("--check")) {
  if (current !== bundle) {
    console.error(
      "build-js: assets/js/main.js does not match assets/js/src/.\n" +
        "  Run: node scripts/build-js.js",
    );
    process.exit(1);
  }
  console.log(`build-js: main.js matches ${files} modules`);
} else if (current === bundle) {
  console.log(`build-js: main.js already current (${files} modules)`);
} else {
  fs.writeFileSync(OUT, bundle);
  console.log(
    `build-js: ${files} modules -> main.js (${(Buffer.byteLength(bundle) / 1024).toFixed(1)}KB)`,
  );
}
