/**
 * Concatenate assets/css/src/*.css into the single assets/css/styles.css the
 * page loads.
 *
 * The source is split so it can be found and edited; the output is one file
 * because the page is served over one connection and mobile already loses
 * around 700ms to render-blocking CSS. Splitting the SERVED file into several
 * <link> tags, or using @import, would add a serial round trip each and make
 * the number Lighthouse already complains about worse. Neither is a trade worth
 * making for authoring comfort.
 *
 * Order is the cascade, and the numeric filename prefixes are that order. The
 * later files depend on it: 07-wide and 08-small override rules set in
 * 03-intro through 06-footer, and 09-print overrides nearly everything. Renaming
 * a file so it sorts differently changes the page.
 *
 *   node scripts/build-css.js           write styles.css
 *   node scripts/build-css.js --check   verify styles.css matches the source
 *
 * --check exists for CI: if someone edits the built file by hand instead of the
 * source, the next build silently discards their change. This turns that into a
 * failure with a message.
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SRC = path.join(ROOT, "assets", "css", "src");
const OUT = path.join(ROOT, "assets", "css", "styles.css");

const BANNER = `/* Generated by scripts/build-css.js from assets/css/src/. Do not edit:
   the next build overwrites it. Edit the partial instead. */\n\n`;

function build() {
  const files = fs
    .readdirSync(SRC)
    .filter((f) => f.endsWith(".css"))
    .sort();
  if (!files.length) throw new Error("no partials in assets/css/src");
  const body = files
    .map((f) => fs.readFileSync(path.join(SRC, f), "utf8").replace(/\s*$/, ""))
    .join("\n\n");
  return { files, css: BANNER + body + "\n" };
}

const { files, css } = build();
const check = process.argv.includes("--check");
const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";

if (check) {
  if (current !== css) {
    console.error(
      "build-css: assets/css/styles.css does not match assets/css/src/.\n" +
        "  Something edited the built file directly, or a partial changed without a rebuild.\n" +
        "  Run: node scripts/build-css.js",
    );
    process.exit(1);
  }
  console.log(`build-css: styles.css matches ${files.length} partials`);
} else {
  if (current === css) {
    console.log(`build-css: styles.css already current (${files.length} partials)`);
  } else {
    fs.writeFileSync(OUT, css);
    const kb = (Buffer.byteLength(css) / 1024).toFixed(1);
    console.log(`build-css: ${files.length} partials -> styles.css (${kb}KB)`);
  }
}
